import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`capabilities_kicker\` text DEFAULT 'Capabilities';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`capabilities_headline\` text DEFAULT 'Strategy and execution, assembled around the brief.';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`capabilities_intro\` text DEFAULT 'ETÉRA brings the relevant disciplines together as one considered practice, with the approach and team shaped for each project.';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`group_labels_brand_culture\` text DEFAULT 'Brand Culture';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`group_labels_creative_visual\` text DEFAULT 'Creative & Visual';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`group_labels_content_influence\` text DEFAULT 'Content & Influence';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`group_labels_experiences_partnerships\` text DEFAULT 'Experiences & Partnerships';`)
  await db.run(sql`ALTER TABLE \`services_page\` ADD \`group_labels_digital_growth\` text DEFAULT 'Digital & Growth';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_capabilities_kicker\` text DEFAULT 'Capabilities';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_capabilities_headline\` text DEFAULT 'Strategy and execution, assembled around the brief.';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_capabilities_intro\` text DEFAULT 'ETÉRA brings the relevant disciplines together as one considered practice, with the approach and team shaped for each project.';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_group_labels_brand_culture\` text DEFAULT 'Brand Culture';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_group_labels_creative_visual\` text DEFAULT 'Creative & Visual';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_group_labels_content_influence\` text DEFAULT 'Content & Influence';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_group_labels_experiences_partnerships\` text DEFAULT 'Experiences & Partnerships';`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` ADD \`version_group_labels_digital_growth\` text DEFAULT 'Digital & Growth';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_heading\` text DEFAULT 'Tell us what you are shaping.';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_help\` text DEFAULT 'Complete the form to prepare a project inquiry in your email app. Nothing is sent until you review and send the message.';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_name\` text DEFAULT 'Full Name';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_brand\` text DEFAULT 'Company Name (if applicable)';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_email\` text DEFAULT 'Email Address';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_services\` text DEFAULT 'What can we help with?';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_services_help\` text DEFAULT 'Select all that apply';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_project\` text DEFAULT 'Tell us about the project';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_budget\` text DEFAULT 'Budget (optional)';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_additional\` text DEFAULT 'Additional information (optional)';`)
  await db.run(sql`ALTER TABLE \`contact_page\` ADD \`inquiry_labels_submit\` text DEFAULT 'Send Inquiry';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_heading\` text DEFAULT 'Tell us what you are shaping.';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_help\` text DEFAULT 'Complete the form to prepare a project inquiry in your email app. Nothing is sent until you review and send the message.';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_name\` text DEFAULT 'Full Name';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_brand\` text DEFAULT 'Company Name (if applicable)';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_email\` text DEFAULT 'Email Address';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_services\` text DEFAULT 'What can we help with?';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_services_help\` text DEFAULT 'Select all that apply';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_project\` text DEFAULT 'Tell us about the project';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_budget\` text DEFAULT 'Budget (optional)';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_additional\` text DEFAULT 'Additional information (optional)';`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` ADD \`version_inquiry_labels_submit\` text DEFAULT 'Send Inquiry';`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`capabilities_kicker\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`capabilities_headline\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`capabilities_intro\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`group_labels_brand_culture\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`group_labels_creative_visual\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`group_labels_content_influence\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`group_labels_experiences_partnerships\`;`)
  await db.run(sql`ALTER TABLE \`services_page\` DROP COLUMN \`group_labels_digital_growth\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_capabilities_kicker\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_capabilities_headline\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_capabilities_intro\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_group_labels_brand_culture\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_group_labels_creative_visual\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_group_labels_content_influence\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_group_labels_experiences_partnerships\`;`)
  await db.run(sql`ALTER TABLE \`_services_page_v\` DROP COLUMN \`version_group_labels_digital_growth\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_heading\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_help\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_name\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_brand\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_email\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_services\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_services_help\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_project\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_budget\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_additional\`;`)
  await db.run(sql`ALTER TABLE \`contact_page\` DROP COLUMN \`inquiry_labels_submit\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_heading\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_help\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_name\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_brand\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_email\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_services\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_services_help\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_project\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_budget\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_additional\`;`)
  await db.run(sql`ALTER TABLE \`_contact_page_v\` DROP COLUMN \`version_inquiry_labels_submit\`;`)
}
