/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    people: Person;
    partners: Partner;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'work-page': WorkPage;
    'atelier-page': AtelierPage;
    'services-page': ServicesPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    'atelier-page': AtelierPageSelect<false> | AtelierPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  area: 'brand-culture' | 'creative-visual' | 'content-influence' | 'experiences-partnerships' | 'digital-growth';
  summary: string;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  clientName: string;
  projectName: string;
  /**
   * URL-safe project identifier, for example brand-campaign.
   */
  slug: string;
  year?: string | null;
  sortOrder?: number | null;
  services?: (string | Service)[] | null;
  heroImage?: (string | null) | Media;
  overview?: string | null;
  context?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        asset: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  collaborators?:
    | {
        role?: string | null;
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Legacy/future people records. Edit the visible founder cards in The Atelier Page → Team Members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  name: string;
  role: string;
  bio?: string | null;
  portrait?: (string | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  logo?: (string | null) | Media;
  summary?: string | null;
  url?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  partners?: {
    /**
     * Allow clients to find partners.
     */
    find?: boolean | null;
    /**
     * Allow clients to create partners.
     */
    create?: boolean | null;
    /**
     * Allow clients to update partners.
     */
    update?: boolean | null;
  };
  people?: {
    /**
     * Allow clients to find people.
     */
    find?: boolean | null;
    /**
     * Allow clients to create people.
     */
    create?: boolean | null;
    /**
     * Allow clients to update people.
     */
    update?: boolean | null;
  };
  projects?: {
    /**
     * Allow clients to find projects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create projects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update projects.
     */
    update?: boolean | null;
  };
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
  };
  atelierPage?: {
    /**
     * Allow clients to find atelier-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update atelier-page global.
     */
    update?: boolean | null;
  };
  contactPage?: {
    /**
     * Allow clients to find contact-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update contact-page global.
     */
    update?: boolean | null;
  };
  homePage?: {
    /**
     * Allow clients to find home-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update home-page global.
     */
    update?: boolean | null;
  };
  servicesPage?: {
    /**
     * Allow clients to find services-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update services-page global.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  workPage?: {
    /**
     * Allow clients to find work-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update work-page global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  area?: T;
  summary?: T;
  details?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  clientName?: T;
  projectName?: T;
  slug?: T;
  year?: T;
  sortOrder?: T;
  services?: T;
  heroImage?: T;
  overview?: T;
  context?: T;
  approach?: T;
  results?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        asset?: T;
        caption?: T;
        id?: T;
      };
  collaborators?:
    | T
    | {
        role?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  portrait?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  summary?: T;
  url?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  partners?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  people?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  projects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  atelierPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  contactPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  homePage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  servicesPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  workPage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroKicker: string;
  heroHeadline: string;
  heroSupportingCopy: string;
  heroAdditionalCopy?: string | null;
  heroCTA: string;
  /**
   * Background video. Leave empty to use the existing studio video.
   */
  heroVideo?: (string | null) | Media;
  /**
   * Still image shown while the video loads or autoplay is unavailable.
   */
  heroPoster?: (string | null) | Media;
  atelierPreviewImage?: (string | null) | Media;
  /**
   * The preview heading and introduction use the Atelier page's headline and introduction.
   */
  atelierLinkLabel: string;
  servicesHeading: string;
  servicesIntro: string;
  servicesLinkLabel: string;
  partnersHeading: string;
  methodSteps: {
    label: string;
    id?: string | null;
  }[];
  featuredProjects?: (string | Project)[] | null;
  featuredPartners?: (string | Partner)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: string;
  kicker: string;
  headline: string;
  intro: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atelier-page".
 */
export interface AtelierPage {
  id: string;
  copy: {
    storyLabel: string;
    storyHeading: string;
    storyAdditional: string;
    teamHeading: string;
    teamIntro: string;
    methodHeading: string;
    methodIntro: string;
    servicesLink: string;
  };
  storyImage?: (string | null) | Media;
  methodLogo?: (string | null) | Media;
  methodSteps?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  kicker: string;
  headline: string;
  intro: string;
  aetherNarrative?: string | null;
  /**
   * The core team shown on the Atelier page. Add, remove or reorder people here.
   */
  teamMembers?:
    | {
        name: string;
        position: string;
        description: string;
        portrait?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  featuredPeople?: (string | Person)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: string;
  kicker: string;
  headline: string;
  intro?: string | null;
  capabilitiesKicker: string;
  capabilitiesHeadline: string;
  capabilitiesIntro?: string | null;
  groupLabels: {
    brandCulture: string;
    creativeVisual: string;
    contentInfluence: string;
    experiencesPartnerships: string;
    digitalGrowth: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  copy: {
    bookingKicker: string;
    bookingHeading: string;
    bookingIntro: string;
    bookingFrameTitle: string;
  };
  serviceOptions: {
    label: string;
    id?: string | null;
  }[];
  kicker: string;
  headline: string;
  intro: string;
  email: string;
  inquiryLabels: {
    ready: string;
    openDraft: string;
    nameError: string;
    emailError: string;
    servicesError: string;
    projectError: string;
    heading: string;
    help: string;
    name: string;
    brand: string;
    email: string;
    services: string;
    servicesHelp: string;
    project: string;
    budget: string;
    additional: string;
    submit: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  copy: {
    home: string;
    atelier: string;
    services: string;
    contact: string;
    project: string;
    ctaLineOne: string;
    ctaLineTwo: string;
    copyright: string;
    terms: string;
    privacy: string;
    cookies: string;
    menu: string;
    close: string;
    skip: string;
  };
  redLogo?: (string | null) | Media;
  whiteLogo?: (string | null) | Media;
  contactEmail: string;
  bookingURL?: string | null;
  footerTagline: string;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: string;
  relatedPoliciesLabel: string;
  terms: {
    title: string;
    /**
     * Edit the approved document using headings, paragraphs and lists.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  privacy: {
    title: string;
    /**
     * Edit the approved document using headings, paragraphs and lists.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  cookies: {
    title: string;
    /**
     * Edit the approved document using headings, paragraphs and lists.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroHeadline?: T;
  heroSupportingCopy?: T;
  heroAdditionalCopy?: T;
  heroCTA?: T;
  heroVideo?: T;
  heroPoster?: T;
  atelierPreviewImage?: T;
  atelierLinkLabel?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  servicesLinkLabel?: T;
  partnersHeading?: T;
  methodSteps?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featuredProjects?: T;
  featuredPartners?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  kicker?: T;
  headline?: T;
  intro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atelier-page_select".
 */
export interface AtelierPageSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        storyLabel?: T;
        storyHeading?: T;
        storyAdditional?: T;
        teamHeading?: T;
        teamIntro?: T;
        methodHeading?: T;
        methodIntro?: T;
        servicesLink?: T;
      };
  storyImage?: T;
  methodLogo?: T;
  methodSteps?:
    | T
    | {
        label?: T;
        id?: T;
      };
  kicker?: T;
  headline?: T;
  intro?: T;
  aetherNarrative?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        description?: T;
        portrait?: T;
        id?: T;
      };
  featuredPeople?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  kicker?: T;
  headline?: T;
  intro?: T;
  capabilitiesKicker?: T;
  capabilitiesHeadline?: T;
  capabilitiesIntro?: T;
  groupLabels?:
    | T
    | {
        brandCulture?: T;
        creativeVisual?: T;
        contentInfluence?: T;
        experiencesPartnerships?: T;
        digitalGrowth?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        bookingKicker?: T;
        bookingHeading?: T;
        bookingIntro?: T;
        bookingFrameTitle?: T;
      };
  serviceOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  kicker?: T;
  headline?: T;
  intro?: T;
  email?: T;
  inquiryLabels?:
    | T
    | {
        ready?: T;
        openDraft?: T;
        nameError?: T;
        emailError?: T;
        servicesError?: T;
        projectError?: T;
        heading?: T;
        help?: T;
        name?: T;
        brand?: T;
        email?: T;
        services?: T;
        servicesHelp?: T;
        project?: T;
        budget?: T;
        additional?: T;
        submit?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  copy?:
    | T
    | {
        home?: T;
        atelier?: T;
        services?: T;
        contact?: T;
        project?: T;
        ctaLineOne?: T;
        ctaLineTwo?: T;
        copyright?: T;
        terms?: T;
        privacy?: T;
        cookies?: T;
        menu?: T;
        close?: T;
        skip?: T;
      };
  redLogo?: T;
  whiteLogo?: T;
  contactEmail?: T;
  bookingURL?: T;
  footerTagline?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  relatedPoliciesLabel?: T;
  terms?:
    | T
    | {
        title?: T;
        body?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        body?: T;
      };
  cookies?:
    | T
    | {
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}